on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  APP_NAME: ${{ secrets.CONTAINER_NAME }}
  ARTIFACT_NAME: app.tar
  TAG: latest

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t {{ secrets.CONTAINER_NAME }}:{{ env.TAG }} .

      - name: Save docker image artifact (tar)
        run: docker save --output {{ env.ARTIFACT_NAME }} {{ secrets.CONTAINER_NAME }}:{{ env.TAG }}

      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          port: ${{ '22' }}
          connect_timeout: 10s
          scp: |
            '{{ env.ARTIFACT_NAME }}' => {{ secrets.SERVER_PATH }}
          last_ssh: |-
            docker stop {{ secrets.CONTAINER_NAME }} || true
            docker rm {{ secrets.CONTAINER_NAME }} || true
            docker rmi {{ secrets.CONTAINER_NAME }}:{{ env.TAG }} || true
            nohup docker load --input {{ secrets.SERVER_PATH }}/{{ env.ARTIFACT_NAME }}
            docker run -d -p 3000:3000 --name {{ secrets.CONTAINER_NAME }} {{ secrets.CONTAINER_NAME }}:{{ env.TAG }}